# -*- coding: utf-8 -*-
"""RPI-GPT Vector Embedder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0OAtngzzehjUyAkbudnamt9068Xb6gB

##Embedding Function
"""

